spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 5MB

aws-property:
  access-key: 123456677
  secret-key: 123456782
  region: ap-northeast-2

jwt:
  secret: jangchungdongwangjokbalbossam1234
